# This file was generated by GoReleaser. DO NOT EDIT.
cask "aimd" do
  version "0.1.0-alpha.4"

  on_macos do
    on_intel do
      sha256 "4f68a9ece2a6ba1b62d2ff5072c058a93b29d9e4004eec023f7128e0422d8d38"
      url "https://github.com/CyberSecAuto-Labs/aimd/releases/download/v#{version}/aimd_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7a1cfbd37919321ce94a561cd772e593bc99c30b2ea68c1b8fb3ef8f91a20921"
      url "https://github.com/CyberSecAuto-Labs/aimd/releases/download/v#{version}/aimd_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6baa2de0e6f3c611764c9e95da1a5c9df2cd852482c9d36d9e161e008dafdac2"
      url "https://github.com/CyberSecAuto-Labs/aimd/releases/download/v#{version}/aimd_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "83e5585506b9f87422c5d98e8e15e8f6d1ba053524410e9a40cb3cd9f744d35a"
      url "https://github.com/CyberSecAuto-Labs/aimd/releases/download/v#{version}/aimd_linux_arm64.tar.gz"
    end
  end

  name "aimd"
  desc "Private AI context overlays for Git repositories"
  homepage "https://github.com/CyberSecAuto-Labs/aimd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aimd"
  bash_completion "completions/aimd.bash"
  fish_completion "completions/aimd.fish"
  zsh_completion "completions/aimd.zsh"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aimd"]
    end
  end

  zap trash: [
      "~/.aimd",
    ]

  caveats <<~EOS
    `brew uninstall --zap aimd` moves the store (~/.aimd) to the Trash. Any project
    still tracking files will be left with broken symlinks and stale
    .git/info/exclude entries — Homebrew cannot reach into project directories to
    clean those up. Before uninstalling, restore the real files: run
    `aimd status --all` to list tracked projects, then in each one run
    `aimd untrack <file>` (restoring is the default) for the files it tracks.
  EOS
end
