# This file was generated by GoReleaser. DO NOT EDIT.
cask "aimd" do
  version "0.1.0-alpha.10"

  on_macos do
    on_intel do
      sha256 "939dd52b5364d84ae11144adbe525a069641102aaabb33d7e9d3cd5d8dcd016a"
      url "https://github.com/CyberSecAuto-Labs/aimd/releases/download/v#{version}/aimd_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "231d608a35517b23d095aa0b156c8dcd9dbd6e108b42922fd7d60c6653ee195c"
      url "https://github.com/CyberSecAuto-Labs/aimd/releases/download/v#{version}/aimd_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "18f901a1de1229a488c49dcb2c7bc22ace6a4820baa40921fe47628606c939ca"
      url "https://github.com/CyberSecAuto-Labs/aimd/releases/download/v#{version}/aimd_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9e9c27c43ecb0784e5123d91e1a15a8f5c22549a51ac8a85271173f2fefa2ed8"
      url "https://github.com/CyberSecAuto-Labs/aimd/releases/download/v#{version}/aimd_linux_arm64.tar.gz"
    end
  end

  name "aimd"
  desc "Private AI context overlays for Git repositories"
  homepage "https://github.com/CyberSecAuto-Labs/aimd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aimd"
  bash_completion "completions/aimd.bash"
  fish_completion "completions/aimd.fish"
  zsh_completion "completions/aimd.zsh"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aimd"]
    end
  end

  zap trash: [
      "~/.aimd",
    ]

  caveats <<~EOS
    `brew uninstall --zap aimd` moves the store (~/.aimd) to the Trash. Any project
    still tracking files will be left with broken symlinks and stale
    .git/info/exclude entries — Homebrew cannot reach into project directories to
    clean those up. Before uninstalling, run `aimd reset` to restore every tracked
    file in every project on this machine back to a real file.
  EOS
end
