# This file was generated by GoReleaser. DO NOT EDIT.
cask "aimd" do
  version "0.1.0-alpha.6"

  on_macos do
    on_intel do
      sha256 "bab6cd272c0ea42078b20d2c25e798848d79dc7bfa58fc3b406c2b2ba0b6c74e"
      url "https://github.com/CyberSecAuto-Labs/aimd/releases/download/v#{version}/aimd_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "419034676de181dd74c2fc442a72f2578d2bf0254580c816618abc040d9a2d20"
      url "https://github.com/CyberSecAuto-Labs/aimd/releases/download/v#{version}/aimd_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "44a221a8cdbaa486fd4dd8cfbd7ac199d7048b8818b27cfe25fd3e9666f5fda3"
      url "https://github.com/CyberSecAuto-Labs/aimd/releases/download/v#{version}/aimd_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f8b3be636894ca330f6294abb3033fdc2699ac93df35978fa815e112edb142ad"
      url "https://github.com/CyberSecAuto-Labs/aimd/releases/download/v#{version}/aimd_linux_arm64.tar.gz"
    end
  end

  name "aimd"
  desc "Private AI context overlays for Git repositories"
  homepage "https://github.com/CyberSecAuto-Labs/aimd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aimd"
  bash_completion "completions/aimd.bash"
  fish_completion "completions/aimd.fish"
  zsh_completion "completions/aimd.zsh"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aimd"]
    end
  end

  zap trash: [
      "~/.aimd",
    ]

  caveats <<~EOS
    `brew uninstall --zap aimd` moves the store (~/.aimd) to the Trash. Any project
    still tracking files will be left with broken symlinks and stale
    .git/info/exclude entries — Homebrew cannot reach into project directories to
    clean those up. Before uninstalling, run `aimd reset` to restore every tracked
    file in every project on this machine back to a real file.
  EOS
end
